import type { Session } from 'electron'
import { app } from 'electron'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

export const DEFAULT_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

export interface FetchOptions {
  headers?: Record<string, string>
  range?: string
  signal?: AbortSignal
  method?: string
  timeoutMs?: number
}

/** 다운로드 전용 fetch. 사용자 헤더(Referer/Cookie 등)를 그대로 전달하고 압축을 끈다. */
export async function fetchMedia(url: string, opts: FetchOptions = {}): Promise<Response> {
  const headers: Record<string, string> = {
    'User-Agent': DEFAULT_UA,
    Accept: '*/*',
    'Accept-Encoding': 'identity',
    ...normalizeHeaders(opts.headers)
  }
  if (opts.range) headers.Range = opts.range
  let signal = opts.signal
  let timer: NodeJS.Timeout | undefined
  if (opts.timeoutMs) {
    const controller = new AbortController()
    timer = setTimeout(() => controller.abort(new Error('연결 시간이 초과되었습니다')), opts.timeoutMs)
    if (opts.signal) opts.signal.addEventListener('abort', () => controller.abort(opts.signal?.reason), { once: true })
    signal = controller.signal
  }
  try {
    return await fetch(url, { method: opts.method ?? 'GET', headers, signal, redirect: 'follow' })
  } finally {
    if (timer) clearTimeout(timer)
  }
}

export function normalizeHeaders(h?: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {}
  if (!h) return out
  for (const [k, v] of Object.entries(h)) {
    if (!v) continue
    const key = k.toLowerCase()
    if (['host', 'content-length', 'connection', 'accept-encoding', 'range', 'transfer-encoding'].includes(key)) continue
    out[canonical(key)] = v
  }
  return out
}

function canonical(key: string): string {
  return key
    .split('-')
    .map((s) => (s ? s[0].toUpperCase() + s.slice(1) : s))
    .join('-')
}

export function headerValue(h: Record<string, string> | undefined, name: string): string | undefined {
  if (!h) return undefined
  const lower = name.toLowerCase()
  for (const [k, v] of Object.entries(h)) if (k.toLowerCase() === lower) return v
  return undefined
}

// ---------- 세션 쿠키 → 헤더/파일 ----------

function cookieMatches(cookie: Electron.Cookie, host: string, secure: boolean): boolean {
  const domain = (cookie.domain ?? '').replace(/^\./, '').toLowerCase()
  if (!domain) return false
  if (host !== domain && !host.endsWith(`.${domain}`)) return false
  if (cookie.secure && !secure) return false
  return true
}

export async function cookieHeaderFor(session: Session | null, url: string): Promise<string | undefined> {
  if (!session) return undefined
  try {
    const u = new URL(url)
    const cookies = await session.cookies.get({})
    const list = cookies.filter((c) => cookieMatches(c, u.hostname.toLowerCase(), u.protocol === 'https:'))
    if (!list.length) return undefined
    return list.map((c) => `${c.name}=${c.value}`).join('; ')
  } catch {
    return undefined
  }
}

/** yt-dlp 용 Netscape 형식 쿠키 파일을 만든다. 쿠키가 없으면 undefined. */
export async function exportCookieFile(session: Session | null, url: string): Promise<string | undefined> {
  if (!session) return undefined
  try {
    const u = new URL(url)
    const host = u.hostname.toLowerCase()
    const cookies = (await session.cookies.get({})).filter((c) => {
      const domain = (c.domain ?? '').replace(/^\./, '').toLowerCase()
      if (!domain) return false
      // 같은 사이트 계열 쿠키를 넉넉하게 포함 (서브도메인 양방향)
      return host === domain || host.endsWith(`.${domain}`) || domain.endsWith(`.${host}`) || sameRoot(host, domain)
    })
    if (!cookies.length) return undefined
    const lines = ['# Netscape HTTP Cookie File', '# Generated by Video Downloader', '']
    for (const c of cookies) {
      const domain = c.domain ?? host
      const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE'
      const exp = c.expirationDate ? Math.floor(c.expirationDate) : 0
      lines.push([domain, includeSub, c.path ?? '/', c.secure ? 'TRUE' : 'FALSE', String(exp), c.name, c.value].join('\t'))
    }
    const dir = path.join(app.getPath('userData'), 'cookies')
    await fs.mkdir(dir, { recursive: true })
    const file = path.join(dir, `${crypto.createHash('md5').update(host).digest('hex')}.txt`)
    await fs.writeFile(file, lines.join('\n') + '\n', 'utf8')
    return file
  } catch {
    return undefined
  }
}

function sameRoot(a: string, b: string): boolean {
  const ra = a.split('.').slice(-2).join('.')
  const rb = b.split('.').slice(-2).join('.')
  return ra === rb && ra.includes('.')
}
